# Generated by Django 4.1.3 on 2022-11-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecuteCodeV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exe_result", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.question",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecuteCodeV1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("save_type", models.CharField(max_length=1)),
                ("exe_result", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.question",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluateCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plagiarism", models.TextField()),
                ("function", models.TextField()),
                ("efficiency", models.TextField()),
                ("readability", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.question",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckTestcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.CharField(max_length=10)),
                ("msg", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.question",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
    ]
