# Generated by Django 4.1.2 on 2022-11-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('course', models.IntegerField()),
                ('question', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=200)),
                ('testcase', models.CharField(max_length=200)),
                ('hint', models.CharField(max_length=512)),
                ('duedate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_pwd', models.IntegerField()),
                ('user_type', models.SmallIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_org', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('question', models.IntegerField()),
                ('save1', models.TextField()),
            ],
        ),
    ]
