<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-08 04:48
=======
# Generated by Django 4.1 on 2022-11-08 06:16
>>>>>>> 6010714e6cc94896e2cd5ff0085b906a09050d76

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('code', models.TextField()),
=======
                ('save1', models.TextField()),
>>>>>>> 6010714e6cc94896e2cd5ff0085b906a09050d76
            ],
        ),
    ]
