# Generated by Django 4.1.2 on 2022-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skeleton',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='save2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='save3',
            field=models.TextField(default=''),
        ),
    ]
