# Generated by Django 4.1.3 on 2022-11-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_course_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                db_column="course",
                help_text="프로그래밍기초실습",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course1",
                to="mainapp.course",
            ),
        ),
    ]
