# Generated by Django 4.1.3 on 2022-11-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_question_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="id",),
        migrations.AlterField(
            model_name="course",
            name="course",
            field=models.CharField(
                help_text="예: SWE3002-41",
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
