# Generated by Django 4.1.3 on 2022-11-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course",
                    models.CharField(
                        help_text="예: SWE3002-41",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_name",
                    models.CharField(help_text="예: 소프트웨어공학개론", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question",
                    models.CharField(
                        help_text="예: 프로그래밍기초실습_week2",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skeleton", models.TextField(help_text="스켈레톤 코드")),
                ("answer", models.CharField(max_length=1000)),
                ("testcase", models.CharField(max_length=100)),
                (
                    "reference",
                    models.CharField(help_text="문제 설명 밑의 참고사항", max_length=300),
                ),
                ("duedate", models.DateTimeField(help_text="마감기한")),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course",
                        help_text="프로그래밍기초실습",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="mainapp.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.EmailField(
                        help_text="사용자가 가입할 때 쓰는 이메일을 id로 사용하기로 했음",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(help_text="예: 홍길동", max_length=50)),
                (
                    "user_pwd",
                    models.CharField(help_text="admin비번은: 1q2w3e4r", max_length=50),
                ),
                ("user_type", models.BooleanField(help_text="학습자: True, 교수자: False")),
                ("user_org", models.CharField(help_text="예: 소프트웨어학과", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("save1", models.TextField()),
                ("save2", models.TextField()),
                ("save3", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.question",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission",
                    models.BooleanField(help_text="제출: 1, 미제출: 0, null값 가능"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.question",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                help_text="예: sunkyun12@skku.edu",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="mainapp.user",
            ),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(help_text="글을 남긴 시간")),
                ("comment", models.TextField(help_text="글 내용")),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.course",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user",
                    ),
                ),
            ],
        ),
    ]
