# Generated by Django 4.1.2 on 2022-11-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', help_text='예: sunkyun12@skku.edu', on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='save1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='save2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='save3',
            field=models.TextField(null=True),
        ),
    ]
