# Generated by Django 4.1.2 on 2022-12-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_course_user_id_alter_userdata_save1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keyword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
