# Generated by Django 4.1.2 on 2022-11-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_chat_comment_alter_chat_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
    ]
